export const products = [
    {
        id: 1,
        name: "KeyStaxx Artisan Keyboard 1",
        type: "Mechanical",
        material: "Aluminum",
        switches: "Cherry MX Red",
        keyCaps: "PBT Keycaps",
        connection: "USB-C",
      },
      {
        id: 2,
        name: "KeyStaxx Mechanical Keyboard 2",
        type: "Mechanical",
        material: "Plastic",
        switches: "Gateron Blue",
        keyCaps: "ABS Keycaps",
        connection: "Wired USB",
      },
      {
        id: 3,
        name: "KeyStaxx Wireless Keyboard 3",
        type: "Mechanical",
        material: "Metal",
        switches: "Kailh Box White",
        keyCaps: "PBT Keycaps",
        connection: "Bluetooth",
      },
      {
        id: 4,
        name: "KeyStaxx Classic Keyboard 4",
        type: "Mechanical",
        material: "Steel",
        switches: "Razer Green",
        keyCaps: "ABS Keycaps",
        connection: "USB-C",
      },
      {
        id: 5,
        name: "KeyStaxx RGB Keyboard 5",
        type: "Mechanical",
        material: "Plastic",
        switches: "Cherry MX Brown",
        keyCaps: "PBT Keycaps",
        connection: "USB-C",
      },
      {
        id: 6,
        name: "KeyStaxx Compact Keyboard 6",
        type: "Mechanical",
        material: "Aluminum",
        switches: "Gateron Red",
        keyCaps: "PBT Keycaps",
        connection: "Wireless",
      },
      {
        id: 7,
        name: "KeyStaxx Silent Keyboard 7",
        type: "Mechanical",
        material: "Plastic",
        switches: "Cherry MX Silent Red",
        keyCaps: "PBT Keycaps",
        connection: "USB-C",
      },
      {
        id: 8,
        name: "KeyStaxx Gamer Keyboard 8",
        type: "Mechanical",
        material: "Metal",
        switches: "Razer Yellow",
        keyCaps: "ABS Keycaps",
        connection: "Bluetooth",
      },
      {
        id: 9,
        name: "KeyStaxx Custom Keyboard 9",
        type: "Mechanical",
        material: "Aluminum",
        switches: "Kailh Box Brown",
        keyCaps: "PBT Keycaps",
        connection: "USB-C",
      },
      {
        id: 10,
        name: "KeyStaxx Budget Keyboard 10",
        type: "Mechanical",
        material: "Plastic",
        switches: "Outemu Blue",
        keyCaps: "ABS Keycaps",
        connection: "Wired USB",
      },
    ];
  
  
  